name: Python Package using Conda

on:
  workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Install dependencies
      run: |
        pip install GitPython
        pip install pytz
        pip install pandas

    - name: Run test.py
      env:
        user: ${{secrets.user}}
        key: ${{secrets.key}}
      run: |
        python ./GITHUB/test.py
      

